parameters:
    webservice_user_provider.class: Evexias\UserBundle\Security\WebServiceUserProvider
    mailService.class: Evexias\UserBundle\Services\MailService
    LogoutListener.class: Evexias\UserBundle\Service\LogoutListenerService

services:
    
    webservice_user_provider:
        class: %webservice_user_provider.class%
        arguments: ['@service_container']
        
    mailService:
        class: %mailService.class%
        arguments: ['@service_container']
        
    mail_logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [mail]
        calls:
            - [pushHandler, ['@mail_handler']]
            
    mail_handler:
        class: Monolog\Handler\RotatingFileHandler
        arguments: [%kernel.logs_dir%/%kernel.environment%.mailer.log, 10] 