parameters:
#    demo_demo.example.class: Demo\DemoBundle\Example

services:
#    demo_demo.example:
#        class: %demo_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
