<?php

namespace Evexias\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository {
    
    
    public function GetUserByLogin($login) {
        $repository = $this
                ->getEntityManager()
                ->getRepository('EvexiasUserBundle:User');
        
        return $repository->findOneBy(array('login' => $login));
    }

}
